In [7]:
#Importing required libraries
import pandas as pd
import numpy as np
from pathlib import Path
from collections import Counter
import matplotlib as mpl
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [14]:
# Load the dataset
df = pd.read_csv(Path('./Resources/Mental_Health_Data.csv'))
df.head(10)

,ID,AGE,GENDER,COUNTRY_WORKING_IN,WFH,MENTAL_HEALTH_COVERAGE,TECH_COMPANY,MENTAL_HEALTH_OPTIONS_UNDER_COVERAGE,EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES,MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT,PREV_EMPLOYERS_PROVIDE_MENTAL_HEALTH_BENEFITS,AWARENESS_OF_MENTAL_HEALTH_COVERAGE_BY_PREV_EMPLOYERS,PREV_EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES,MENTAL_HEALTH_IDENTITY_HURT_YOUR_CAREER,CURRENT_MENTAL_HEALTH_DISORDER
0,0,39,Male,United Kingdom,Sometimes,Not eligible for coverage,1.0,NaN,No,NaN,"No, none did",N/A (not currently aware),None did,Maybe,No
1,1,29,male,United States of America,Never,No,1.0,Yes,Yes,NaN,"Yes, they all did",I was aware of some,Some did,"No, I don't think it would",Yes
2,2,38,Male,United Kingdom,Always,No,1.0,NaN,No,NaN,"No, none did",N/A (not currently aware),Some did,Maybe,No
3,3,43,male,United Kingdom,Sometimes,NaN,NaN,NaN,NaN,1.0,Some did,N/A (not currently aware),None did,"Yes, I think it would",Yes
4,4,43,Female,United States of America,Sometimes,Yes,0.0,Yes,No,NaN,I don't know,N/A (not currently aware),None did,"Yes, I think it would",Yes
5,5,42,Male,United Kingdom,Sometimes,Yes,1.0,I am not sure,Yes,NaN,"No, none did","Yes, I was aware of all of them",None did,"Yes, I think it would",Yes
6,6,30,M,United States of America,Sometimes,I don't know,1.0,No,No,NaN,Some did,I was aware of some,Some did,"Yes, I think it would",No
7,7,37,female,United States of America,Always,Yes,1.0,Yes,Yes,NaN,Some did,I was aware of some,Some did,Maybe,Yes
8,8,44,Female,United States of America,Sometimes,I don't know,0.0,No,No,NaN,I don't know,N/A (not currently aware),None did,Maybe,Yes
9,9,30,Male,United States of America,Always,NaN,NaN,NaN,NaN,1.0,Some did,I was aware of some,None did,Maybe,Yes

In [16]:
# Basic Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1433 entries, 0 to 1432
Data columns (total 15 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   ID                                                     1433 non-null   int64
 1   AGE                                                    1433 non-null   int64
 2   GENDER                                                 1430 non-null   object
 3   COUNTRY_WORKING_IN                                     1433 non-null   object
 4   WFH                                                    1433 non-null   object
 5   MENTAL_HEALTH_COVERAGE                                 1146 non-null   object
 6   TECH_COMPANY                                           1146 non-null   float64
 7   MENTAL_HEALTH_OPTIONS_UNDER_COVERAGE                   1013 non-null   object
 8   EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES                 1146 non-null   object
 9   MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT     287 non-null    float64
 10  PREV_EMPLOYERS_PROVIDE_MENTAL_HEALTH_BENEFITS          1264 non-null   object
 11  AWARENESS_OF_MENTAL_HEALTH_COVERAGE_BY_PREV_EMPLOYERS  1264 non-null   object
 12  PREV_EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES            1264 non-null   object
 13  MENTAL_HEALTH_IDENTITY_HURT_YOUR_CAREER                1433 non-null   object
 14  CURRENT_MENTAL_HEALTH_DISORDER                         1433 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 168.1+ KB

In [17]:
# Describe the data
df.describe()

,ID,AGE,TECH_COMPANY,MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT
count,1433.00000,1433.000000,1146.000000,287.000000
mean,716.00000,34.286113,0.770506,0.644599
std,413.81578,11.290931,0.420691,0.479471
min,0.00000,3.000000,0.000000,0.000000
25%,358.00000,28.000000,1.000000,0.000000
50%,716.00000,33.000000,1.000000,1.000000
75%,1074.00000,39.000000,1.000000,1.000000
max,1432.00000,323.000000,1.000000,1.000000

In [19]:
# Check for duplicates
df.duplicated().sum()

0

In [20]:
df.shape

(1433, 15)

In [21]:
df.columns

Index(['ID', 'AGE', 'GENDER', 'COUNTRY_WORKING_IN', 'WFH',
       'MENTAL_HEALTH_COVERAGE', 'TECH_COMPANY',
       'MENTAL_HEALTH_OPTIONS_UNDER_COVERAGE',
       'EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES',
       'MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT',
       'PREV_EMPLOYERS_PROVIDE_MENTAL_HEALTH_BENEFITS',
       'AWARENESS_OF_MENTAL_HEALTH_COVERAGE_BY_PREV_EMPLOYERS',
       'PREV_EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES',
       'MENTAL_HEALTH_IDENTITY_HURT_YOUR_CAREER',
       'CURRENT_MENTAL_HEALTH_DISORDER'],
      dtype='object')

In [22]:
# Find null values
df.isnull().sum()

ID                                                          0
AGE                                                         0
GENDER                                                      3
COUNTRY_WORKING_IN                                          0
WFH                                                         0
MENTAL_HEALTH_COVERAGE                                    287
TECH_COMPANY                                              287
MENTAL_HEALTH_OPTIONS_UNDER_COVERAGE                      420
EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES                    287
MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT       1146
PREV_EMPLOYERS_PROVIDE_MENTAL_HEALTH_BENEFITS             169
AWARENESS_OF_MENTAL_HEALTH_COVERAGE_BY_PREV_EMPLOYERS     169
PREV_EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES               169
MENTAL_HEALTH_IDENTITY_HURT_YOUR_CAREER                     0
CURRENT_MENTAL_HEALTH_DISORDER                              0
dtype: int64

In [ ]:
# Drop MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT row

In [ ]:
# Replace null values
# df.replace(np.nan,'0',inplace = True)

In [29]:
# Check datatypes
df.dtypes

ID                                                         int64
AGE                                                        int64
GENDER                                                    object
COUNTRY_WORKING_IN                                        object
WFH                                                       object
MENTAL_HEALTH_COVERAGE                                    object
TECH_COMPANY                                             float64
MENTAL_HEALTH_OPTIONS_UNDER_COVERAGE                      object
EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES                    object
MEDICAL_COVERAGE_INCLUDING_MENTAL_HEALTH_TREATMENT       float64
PREV_EMPLOYERS_PROVIDE_MENTAL_HEALTH_BENEFITS             object
AWARENESS_OF_MENTAL_HEALTH_COVERAGE_BY_PREV_EMPLOYERS     object
PREV_EMPLOYER_OFFER_MENTAL_HEALTH_RESOURCES               object
MENTAL_HEALTH_IDENTITY_HURT_YOUR_CAREER                   object
CURRENT_MENTAL_HEALTH_DISORDER                            object
dtype: object